_wandb:
    value:
        cli_version: 0.27.0
        e:
            xqqrgryv87wge55sz0llyk5vg7gqe9i5:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    macModel: Mac14,2
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "2147483648"
                codePath: src/project_name/train.py
                codePathLocal: src/project_name/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "226050146304"
                email: liuyuxinnj@gmail.com
                executable: /Users/yuxinliu/Desktop/M2/MLops/.venv/bin/python3
                git:
                    commit: 4e1a8f955d94fc032174c5f893dadd2936b19274
                    remote: git@github.com:DucAnhValentinoNguyen/SS26_MLOps_Project_GroupA.git
                host: MacBook-Air-L.local
                memory:
                    total: "8589934592"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/yuxinliu/Desktop/M2/MLops/src/project_name/train.py
                python: CPython 3.11.5
                root: /Users/yuxinliu/Desktop/M2/MLops
                startedAt: "2026-05-17T20:28:33.150469Z"
                writerId: xqqrgryv87wge55sz0llyk5vg7gqe9i5
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 2
                - 14
            "4": 3.11.5
            "5": 0.27.0
            "12": 0.27.0
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 10
lr:
    value: 0.009267048575368511
